### ISSUE TITLE
Android Basics: Dogglers app - Incorrect filename referenced in the documentation

### ISSUE THREAD

**Issue by profess** [google-developer-training/android-basics-kotlin-dogglers-app#17] opened 2022-03-25 00:39 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2

**In which task and step of the codelab can this issue be found?**
Project: Dogglers App: Step 3: Get Started

**Describe the problem**
There is a reference to a file which does not exist: 'horizontal_vertical_list_item.xml'.
The file is actually 'vertical_horizontal_list_item.xml'

**Additional information**
<img width="771" alt="image" src="https://user-images.githubusercontent.com/2918781/160032100-e90f81b3-f468-4323-b7ee-b78c6cfa6f3d.png">

<img width="210" alt="image" src="https://user-images.githubusercontent.com/2918781/160032281-45ede952-34a9-4439-b7c9-cc9b09dc95d2.png">

**Comment by osuleymanova** [comment] 2022-05-27 20:03
Duplicate of #11, #14

**Comment by osuleymanova** [comment] 2022-05-31 18:41
@profess 
Thank you for reaching out to us. The issue is fixed and will be published soon:
![Screen Shot 2022-05-31 at 11 17 58 AM](https://user-images.githubusercontent.com/86437155/171261722-d44ed9bb-b125-4148-893f-9e3c07653d2d.png)

**Closed by osuleymanova** 2022-05-31 18:41 UTC
