### ISSUE TITLE
Android Basics: Wrong File name in Dogglers app

### ISSUE THREAD

**Issue by lorenzsq** [google-developer-training/android-basics-kotlin-dogglers-app#14] opened 2022-03-06 10:55 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2

**Describe the problem**
"horizontal_vertical_list_item.xml" should be "vertical_horizontal_list_item.xml"
In one section of the instructions it says "horizontal_vertical_list_item.xml" but the actual file name is "vertical_horizontal_list_item.xml".

**Comment by osuleymanova** [comment] 2022-05-27 18:45
Duplicate of #11

**Comment by osuleymanova** [comment] 2022-05-31 18:22
@lorenzsq 
Thank you for reaching out to us. The issue is fixed and will be published soon:
![Screen Shot 2022-05-31 at 11 17 58 AM](https://user-images.githubusercontent.com/86437155/171257933-e37a4907-a3c9-45c2-9fcd-73b0ae50de22.png)

**Closed by osuleymanova** 2022-05-31 18:22 UTC
